[digest-daily]
cron = "0 8 * * *"
notebook = "https://github.com/etalab/notebooks/raw/schedule/moderation/moderation.ipynb"
depends_on = [
    { name = "moderation_fn", url = "https://github.com/etalab/notebooks/raw/schedule/moderation/moderation_fn.ipynb" }
]
only_errors = false
pdf = true
# FIXME: change to digest
recipient_alias_dgf = "test"

[digest-weekly]
cron = "30 8 * * 2"
notebook = "https://github.com/etalab/notebooks/raw/schedule/moderation/weekly-digest.ipynb"
depends_on = [
    { name = "moderation_fn", url = "https://github.com/etalab/notebooks/raw/schedule/moderation/moderation_fn.ipynb" }
]
only_errors = false
pdf = true
# FIXME: change to digest
recipient_alias_dgf = "test"

[digest-monthly]
cron = "15 8 25 * *"
notebook = "https://github.com/etalab/notebooks/raw/schedule/moderation/monthly-digest.ipynb"
depends_on = [
    { name = "moderation_fn", url = "https://github.com/etalab/notebooks/raw/schedule/moderation/moderation_fn.ipynb" }
]
only_errors = false
pdf = true
# FIXME: change to digest
recipient_alias_dgf = "test"

[users-creation]
cron = "*/15 * * * *"
notebook = "https://github.com/etalab/notebooks/raw/schedule/moderation/user-creation.ipynb"
only_errors = true
pdf = false

[community-ressources]
cron = "*/15 * * * *"
notebook = "https://github.com/etalab/notebooks/raw/schedule/moderation/community-resources-creation.ipynb"
only_errors = true
pdf = false

[stats-daily]
cron = "12 8 * * *"
notebook = "https://github.com/etalab/notebooks/raw/schedule/stats/piwik-top-daily.ipynb"
only_errors = true
pdf = false
depends_on = [
    { name = "piwik-top", url = "https://github.com/etalab/notebooks/raw/schedule/stats/piwik-top.ipynb" }
]

[stats-weekly]
cron = "29 8 * * 1"
notebook = "https://github.com/etalab/notebooks/raw/schedule/stats/piwik-top-weekly.ipynb"
only_errors = true
pdf = false
depends_on = [
    { name = "piwik-top", url = "https://github.com/etalab/notebooks/raw/schedule/stats/piwik-top.ipynb" }
]

[stats-monthly]
cron = "22 8 1 * *"
notebook = "https://github.com/etalab/notebooks/raw/schedule/stats/piwik-top-monthly.ipynb"
only_errors = true
pdf = false
depends_on = [
    { name = "piwik-top", url = "https://github.com/etalab/notebooks/raw/schedule/stats/piwik-top.ipynb" }
]

[irve]
cron = "42 22 20 * *"
notebook = "https://github.com/etalab/notebooks/raw/schedule/irve/irve.ipynb"
only_errors = false
pdf = false
